apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner
  template:
    metadata:
      labels:
        app: gitlab-runner
    spec:
      containers:
      - name: gitlab-runner
        image: gitlab/gitlab-runner:alpine
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: gitlab-runner-config
          mountPath: /etc/gitlab-runner
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: gitlab-runner-config
        emptyDir: {}
      restartPolicy: Always
